### ISSUE TITLE
func UpdateRole (panic)

### ISSUE THREAD

**Issue by n8tbyte** [antoniopapa/go-admin#1]
panic: reflect: call of reflect.Value.Type on zero Value

**Comment by brockhenrie** [comment]
get rid of the & and it works on the delete statement. that seemed to fix it for me

Before                                                                                                
database.DB.Table("role_permissions").Where("role_id", id).Delete(&result)

After
database.DB.Table("role_permissions").Where("role_id", id).Delete(result)

**Comment by brockhenrie** [comment]
> panic: reflect: call of reflect.Value.Type on zero Value

get rid of the & and it works on the delete statement. that seemed to fix it for me

Before
database.DB.Table("role_permissions").Where("role_id", id).Delete(&result)

After
database.DB.Table("role_permissions").Where("role_id", id).Delete(result)
